name: write
description: bartulem's blog
url: https://bartulem.github.io/write/

feed_items: 5
feed_update_period: weekly
feed_update_frequency: 1

markdown: kramdown
google_analytics: UA-157587935-1
permalink: pretty

paginate: 5
paginate_path: "/write/page:num/"

baseurl: ""




