name: inexile
description: bartulem's blog
url: https://bartulem.github.io/inexile/

sciname: science
scidescription: science blog
sciurl: https://bartulem.github.io/science/
paginate: 5

feed_items: 5
feed_update_period: weekly
feed_update_frequency: 1

markdown: kramdown
permalink: pretty
google_analytics: UA-157587935-1
